application: apptscout
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: scout.wsgi.application
  login: admin
  secure: always
- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: always
- url: /static/
  static_dir: scout/static
  secure: always
  expiration: "0m"
- url: /admin.*
  script: scout.wsgi.application
  secure: always
  login: admin
- url: /.*
  script: scout.wsgi.application
  secure: always
  login: required

skip_files:
- manage.py
- README.md
- install_deps
- requirements.txt
- sitepackages/google_appengine*
- \.storage.*
- (.*)\.pyc